{
  "formatVersion": "1.1",
  "component": {
    "group": "org.niis.xrd4j",
    "module": "client",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.niis.xrd4j",
          "module": "common",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.niis.xrd4j",
          "module": "rest",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-0.6.0.jar",
          "url": "client-0.6.0.jar",
          "size": 100107,
          "sha512": "5493e4d1eece2c06122bfd3a8e78f389e91c1ddb2cc3a7df3285afe733e8489bb2937feb98eba38e920bc6342103b9f40d005deac8769ee0873c1e63721a9fef",
          "sha256": "3633cc62f4850ab3bd55faead86865df89666d698603bda01cf6dd2183e8aab1",
          "sha1": "1282f8a7fb0dc1e6755c897877c9d25a2827f8bb",
          "md5": "58ac6816ac31fec8718bf9a204003099"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.niis.xrd4j",
          "module": "common",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.niis.xrd4j",
          "module": "rest",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "client-0.6.0.jar",
          "url": "client-0.6.0.jar",
          "size": 100107,
          "sha512": "5493e4d1eece2c06122bfd3a8e78f389e91c1ddb2cc3a7df3285afe733e8489bb2937feb98eba38e920bc6342103b9f40d005deac8769ee0873c1e63721a9fef",
          "sha256": "3633cc62f4850ab3bd55faead86865df89666d698603bda01cf6dd2183e8aab1",
          "sha1": "1282f8a7fb0dc1e6755c897877c9d25a2827f8bb",
          "md5": "58ac6816ac31fec8718bf9a204003099"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-0.6.0-sources.jar",
          "url": "client-0.6.0-sources.jar",
          "size": 104992,
          "sha512": "064d8e5048b8a4f9a4d3a2fcc1a9cfa31217266823ed68ac186cf87bafcecd3d879b1908fe5267c0d1f9c0df016d68a5455b2ed798157c1186fd02586943f600",
          "sha256": "53732f957fe892f75d6374023970bcced9a650c40369ee7c6bc244ddb232c62e",
          "sha1": "a123d75627440e17f048099686d4677475fe7a7c",
          "md5": "f25daa3ae89ad4b8bf34765097d1744a"
        }
      ]
    }
  ]
}
