{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.39"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.39"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.39"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.4.jar",
          "url": "spring-boot-starter-tomcat-3.4.4.jar",
          "size": 4794,
          "sha512": "18f5d3193d24d72923173d1f4da8915459bfc9c435e4ed5b11f9fdbfecaebeaeca6b4cd064cf0967fe953e602f7f0c881a4441606f7256c793f30730d536826a",
          "sha256": "fdae817f961cfc561af6f305895a2d334a3986bd4544d469e26a321814edff54",
          "sha1": "4b18ac49cf13ef2c9a98418ebd8fc212a5259da9",
          "md5": "bd11b639d93802bc1038a3e091b432d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.39"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.39"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.39"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.4.jar",
          "url": "spring-boot-starter-tomcat-3.4.4.jar",
          "size": 4794,
          "sha512": "18f5d3193d24d72923173d1f4da8915459bfc9c435e4ed5b11f9fdbfecaebeaeca6b4cd064cf0967fe953e602f7f0c881a4441606f7256c793f30730d536826a",
          "sha256": "fdae817f961cfc561af6f305895a2d334a3986bd4544d469e26a321814edff54",
          "sha1": "4b18ac49cf13ef2c9a98418ebd8fc212a5259da9",
          "md5": "bd11b639d93802bc1038a3e091b432d7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.4-javadoc.jar",
          "url": "spring-boot-starter-tomcat-3.4.4-javadoc.jar",
          "size": 4794,
          "sha512": "16969c31d6c7dfbe4f4cd4952e6e77d24dac14cbb6c9209a39bd48cc6b2a10b065f726ed5041289954e9714f23a69e9a8085af664762af543292bf2609194904",
          "sha256": "64f0c1835fade1df49dd95eb3935e54b651e1b26a92424dae62adfa147ce0c6c",
          "sha1": "2b2079be4fd8f44269b24ddd04f2972603c05b0d",
          "md5": "b29e33a66365e9ffba04ab388a5a670f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.4-sources.jar",
          "url": "spring-boot-starter-tomcat-3.4.4-sources.jar",
          "size": 4794,
          "sha512": "16969c31d6c7dfbe4f4cd4952e6e77d24dac14cbb6c9209a39bd48cc6b2a10b065f726ed5041289954e9714f23a69e9a8085af664762af543292bf2609194904",
          "sha256": "64f0c1835fade1df49dd95eb3935e54b651e1b26a92424dae62adfa147ce0c6c",
          "sha1": "2b2079be4fd8f44269b24ddd04f2972603c05b0d",
          "md5": "b29e33a66365e9ffba04ab388a5a670f"
        }
      ]
    }
  ]
}
