---
excludes:
  paths:
  - pattern: "3RD-PARTY-NOTICES.txt"
    reason: "OTHER"
    comment: "File including 3rd party license notices."

  - pattern: "images/**"
    reason: "DOCUMENTATION_OF"
    comment: "This directory contains images that are not distributed."

  - pattern: "documentation/**"
    reason: "DOCUMENTATION_OF"
    comment: "This directory contains documentation that's not distributed."

  scopes:
  - pattern: "checkstyle"
    reason: "BUILD_DEPENDENCY_OF"
    comment: "Packages for code styling checks (testing) only."

  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "jacocoAgent"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "jacocoAnt"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "test.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."

  - pattern: "annotationProcessor"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileClasspath"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileOnly"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

resolutions:
  rule_violations:
    - message: "commercial license LicenseRef-scancode-proprietary-license in Maven:org.aspectj:aspectjweaver:1.9.6."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "These files are used as per the license terms and therefore license is acquired, that is used within Python, compiled Python, or other languages (such as C) wherein the modified or derived code is exclusively imported into a Python module."

    - message: "proprietary-free license LicenseRef-scancode-efsl-1.0 in Maven:jakarta.annotation:jakarta.annotation-api:1.3.5."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "These specification files, to the extent used, are not modified and therefore used as per the license."
