{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-engine",
    "version": "5.11.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.11.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-engine",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.11.4"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-engine-5.11.4.jar",
          "url": "junit-jupiter-engine-5.11.4.jar",
          "size": 260117,
          "sha512": "a2d5cfaa919504a5013facc3711f79d0f68410f7296f2c7153e14e89c437e2a3a0c408d6d09924b60b6b3b6a17367b0a5f0511044be7abff707a30cfd1d3176b",
          "sha256": "cdf8ac59f3fad774ca738ad03890950eeb91833ef0e8908753177edd26f1581c",
          "sha1": "dc10ec209623986a68ea07f67cdc7d2a65a60355",
          "md5": "ff0242ed33cb684ec5a1d02164c5d26d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.11.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-engine",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.11.4"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-engine-5.11.4.jar",
          "url": "junit-jupiter-engine-5.11.4.jar",
          "size": 260117,
          "sha512": "a2d5cfaa919504a5013facc3711f79d0f68410f7296f2c7153e14e89c437e2a3a0c408d6d09924b60b6b3b6a17367b0a5f0511044be7abff707a30cfd1d3176b",
          "sha256": "cdf8ac59f3fad774ca738ad03890950eeb91833ef0e8908753177edd26f1581c",
          "sha1": "dc10ec209623986a68ea07f67cdc7d2a65a60355",
          "md5": "ff0242ed33cb684ec5a1d02164c5d26d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-engine-5.11.4-javadoc.jar",
          "url": "junit-jupiter-engine-5.11.4-javadoc.jar",
          "size": 387111,
          "sha512": "bc43486bbe694141528344d9c98bcaecf28414254c3db34154968cd69419bc412259fcabc85c00065d689af702c7bd09eff898fa541463f7c704d3f730b0a08f",
          "sha256": "52226d7ec5dc778a07c9c3993e56e53bbc6f758781a69f2ed0ae20905143e69f",
          "sha1": "4f8254cb22ec2e762ee2189df7b97ed347293419",
          "md5": "fccfe69327f9b92039c9307b7db7c0a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-engine-5.11.4-sources.jar",
          "url": "junit-jupiter-engine-5.11.4-sources.jar",
          "size": 134277,
          "sha512": "d888046a3baec771f84a71bae50a77fd493fac89c425af1c9efb44d0031da2ed3b176805bc635a7e2262622de8e1fdedf68998ddbbc35ed02a42264da1945183",
          "sha256": "b2343451cf7f9cd0044b4a614adca1dd88f3a9265256c88a4a6f3b68e65075c8",
          "sha1": "62890d34f46a222a73690cff58bc6ba477ac1214",
          "md5": "d208545f216f73014a7152f2873bffde"
        }
      ]
    }
  ]
}
