{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jsr310",
    "version": "2.18.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.18.3.jar",
          "url": "jackson-datatype-jsr310-2.18.3.jar",
          "size": 131553,
          "sha512": "2b30c783baa27f0aa560bac497be3529c4ed8209e13875e9463c6f520cd1f6b79793b68678e664dc3cba4a0b4adae68ffdc32f8076e9f27bebf9010ccee8b607",
          "sha256": "9511e1992cd41d5bf76be3d888c3538132b34694c98dae87fbb432b4c54e212c",
          "sha1": "c78b86330ac3442be7fc182a15bc0746d22d6d86",
          "md5": "36207e3acfc9c9badf4947110b515dfa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.18.3.jar",
          "url": "jackson-datatype-jsr310-2.18.3.jar",
          "size": 131553,
          "sha512": "2b30c783baa27f0aa560bac497be3529c4ed8209e13875e9463c6f520cd1f6b79793b68678e664dc3cba4a0b4adae68ffdc32f8076e9f27bebf9010ccee8b607",
          "sha256": "9511e1992cd41d5bf76be3d888c3538132b34694c98dae87fbb432b4c54e212c",
          "sha1": "c78b86330ac3442be7fc182a15bc0746d22d6d86",
          "md5": "36207e3acfc9c9badf4947110b515dfa"
        }
      ]
    }
  ]
}
