{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jayway.jsonpath",
    "module": "json-path",
    "version": "2.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-path-2.9.0.jar",
          "url": "json-path-2.9.0.jar",
          "size": 276633,
          "sha512": "9a9dbb2cd36662c8049419ed891290602baeca2549eb7df62122cb20c91e66bc8c2c0e5e13199c4a70bf0b6e62ea4c2601f84e4c79d2af25ff1704481c86740a",
          "sha256": "11a9ee6f88bb31f1450108d1cf6441377dec84aca075eb6bb2343be157575bea",
          "sha1": "37fe2217f577b0b68b18e62c4d17a8858ecf9b69",
          "md5": "e89678d2e4ff45e4f39a97ccd0223719"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.11"
          }
        }
      ],
      "files": [
        {
          "name": "json-path-2.9.0.jar",
          "url": "json-path-2.9.0.jar",
          "size": 276633,
          "sha512": "9a9dbb2cd36662c8049419ed891290602baeca2549eb7df62122cb20c91e66bc8c2c0e5e13199c4a70bf0b6e62ea4c2601f84e4c79d2af25ff1704481c86740a",
          "sha256": "11a9ee6f88bb31f1450108d1cf6441377dec84aca075eb6bb2343be157575bea",
          "sha1": "37fe2217f577b0b68b18e62c4d17a8858ecf9b69",
          "md5": "e89678d2e4ff45e4f39a97ccd0223719"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "json-path-2.9.0-javadoc.jar",
          "url": "json-path-2.9.0-javadoc.jar",
          "size": 788952,
          "sha512": "1810b629ae56cb46b83f3eaaa8be5069f40eae8eac4a96c993d444d2ddfe1a99de07c7754dfc626bfc2a3b8b96019cea0c38488382d4c97cf4c9d4b63d7bf37b",
          "sha256": "d2ad89d87ec4a000158f449a17b7f3f942df850060fc13e14bb9e04ef65f8f41",
          "sha1": "46134d59dbae467803e21e5a7ee37d6d8415ca1e",
          "md5": "673f04417d983d5504b823630f588db1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "json-path-2.9.0-sources.jar",
          "url": "json-path-2.9.0-sources.jar",
          "size": 134599,
          "sha512": "5303dc970eaa2f4dd46ca0057d5597cf85335cef9c0b3d107582f22d0d02fb291144834776296b2f4eadd75d2b22fe526afb1c76ea3fa289ef6cac69a44eb225",
          "sha256": "67d18b2ebb7b946c781310b9c3d0232f44b7a98278be28afe62a9e658806d088",
          "sha1": "a1ae84a6b97263c7ea566dfa73d5ac2271743e44",
          "md5": "33e4dd2b8a98dfbfdc0b390bd9ebaf5d"
        }
      ]
    }
  ]
}
