{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.24.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.4.jar",
          "url": "spring-boot-starter-logging-3.4.4.jar",
          "size": 4761,
          "sha512": "d2523e70a5f82965b1e7fdf7746b194e3e0651acefee00e4a9ea60bc31ddb9453ca7234c749986c81fd61c98e1c0dddbf66d7a7677ddba9025d4af532e274270",
          "sha256": "1fcd1236a38b5eebc357527c058070669272b7b60c8394f887db882b4b47a240",
          "sha1": "1a7bbfd57e0b2d0bde8ffd6aa7a0ebd94e4b0aed",
          "md5": "b8e6b12feac79f6581d46e89c00826c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.24.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.4.jar",
          "url": "spring-boot-starter-logging-3.4.4.jar",
          "size": 4761,
          "sha512": "d2523e70a5f82965b1e7fdf7746b194e3e0651acefee00e4a9ea60bc31ddb9453ca7234c749986c81fd61c98e1c0dddbf66d7a7677ddba9025d4af532e274270",
          "sha256": "1fcd1236a38b5eebc357527c058070669272b7b60c8394f887db882b4b47a240",
          "sha1": "1a7bbfd57e0b2d0bde8ffd6aa7a0ebd94e4b0aed",
          "md5": "b8e6b12feac79f6581d46e89c00826c4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.4-javadoc.jar",
          "url": "spring-boot-starter-logging-3.4.4-javadoc.jar",
          "size": 4761,
          "sha512": "42ec1667ed18d13c2ab678fa1464ad76b88378094f4be96db2953e7933459a91b8cbbe5d22c32e637eec23eb81f7f952e1af6ec881863fadfbe75b3ae1d3ed93",
          "sha256": "80da486b48cfd73c7476f66cf2dedfa972168c8970899b11646d5328aef967f7",
          "sha1": "2683cfabf2cfab09a772f416963e6260640f9b01",
          "md5": "f0f93443393e312a6fde6f55e5052c15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.4-sources.jar",
          "url": "spring-boot-starter-logging-3.4.4-sources.jar",
          "size": 4761,
          "sha512": "42ec1667ed18d13c2ab678fa1464ad76b88378094f4be96db2953e7933459a91b8cbbe5d22c32e637eec23eb81f7f952e1af6ec881863fadfbe75b3ae1d3ed93",
          "sha256": "80da486b48cfd73c7476f66cf2dedfa972168c8970899b11646d5328aef967f7",
          "sha1": "2683cfabf2cfab09a772f416963e6260640f9b01",
          "md5": "f0f93443393e312a6fde6f55e5052c15"
        }
      ]
    }
  ]
}
