{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.4.4.jar",
          "url": "spring-boot-test-3.4.4.jar",
          "size": 253740,
          "sha512": "25c104957ded635bf23714af195a90c2c853a3b1acc9e076dce90ea1e6bb62b05729b6ef6e2a35d0436f251a80dd8c76767e17478221720df17d829a3a12fc52",
          "sha256": "bc69584886005c5607d89120fba3750bc689396c12586b6b917e21bd5bb92b15",
          "sha1": "cc93446b14f050793c57ecd74a066ecf9ebac96b",
          "md5": "a542ec8a9900631bb1a8aca5579bd18e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.4.4.jar",
          "url": "spring-boot-test-3.4.4.jar",
          "size": 253740,
          "sha512": "25c104957ded635bf23714af195a90c2c853a3b1acc9e076dce90ea1e6bb62b05729b6ef6e2a35d0436f251a80dd8c76767e17478221720df17d829a3a12fc52",
          "sha256": "bc69584886005c5607d89120fba3750bc689396c12586b6b917e21bd5bb92b15",
          "sha1": "cc93446b14f050793c57ecd74a066ecf9ebac96b",
          "md5": "a542ec8a9900631bb1a8aca5579bd18e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.4.4-javadoc.jar",
          "url": "spring-boot-test-3.4.4-javadoc.jar",
          "size": 418908,
          "sha512": "df8ed21cab2da924a9f407172ba3cc3b32718c68b2e860db254f3621ae59adcaca7e1da620d2381c32deda7f556125c8b85b042616166e1e1717fc860aeb741e",
          "sha256": "db87cc1a46d5fb0cdef02c8901c0cc1b12258645cf34d1cee39f82909e40473a",
          "sha1": "d5e441b31a4dedb85e61903c868ed580c611aedc",
          "md5": "2eea20225858b7f0ebdbcb6fe4840d13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.4.4-sources.jar",
          "url": "spring-boot-test-3.4.4-sources.jar",
          "size": 175009,
          "sha512": "6106bdec587b76625a617cf9eef7cdd71d8493ac1df1aae27bb56499d94a5436898fe4936168083be5b587a76fedb091b968704ad0672492ae24ce10c2ac712a",
          "sha256": "0ae9a104ba299ede2aebb447336fe8177fc430e7dffff437ebb83958f3611cc8",
          "sha1": "99d3b629745a1bc18c42f359b32c30a6bda47e5f",
          "md5": "7097549e092f8b1f988409a0b1222d72"
        }
      ]
    }
  ]
}
