{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-yaml",
    "version": "2.18.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.18.3.jar",
          "url": "jackson-dataformat-yaml-2.18.3.jar",
          "size": 54434,
          "sha512": "d42d7c403074c888f201117fdee1970e77bacbde30fafef0deed370c651391e1b1a2be4f1910332e9edf46405ae78ca5782bf48b4a4f5f83a6af03e769c2681c",
          "sha256": "c6523196e1e923dd09a1a3c2ec575d1d3301296a4f005f954e555b1a5c651f39",
          "sha1": "5e15e169c481e2b5dd0d752b390f6675fd1febda",
          "md5": "b12d9f61882b98e2283db0e11d27ab60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.18.3.jar",
          "url": "jackson-dataformat-yaml-2.18.3.jar",
          "size": 54434,
          "sha512": "d42d7c403074c888f201117fdee1970e77bacbde30fafef0deed370c651391e1b1a2be4f1910332e9edf46405ae78ca5782bf48b4a4f5f83a6af03e769c2681c",
          "sha256": "c6523196e1e923dd09a1a3c2ec575d1d3301296a4f005f954e555b1a5c651f39",
          "sha1": "5e15e169c481e2b5dd0d752b390f6675fd1febda",
          "md5": "b12d9f61882b98e2283db0e11d27ab60"
        }
      ]
    }
  ]
}
