{
  "formatVersion": "1.1",
  "component": {
    "group": "org.wiremock",
    "module": "wiremock",
    "version": "3.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-bom",
          "version": {
            "requires": "11.0.24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-servlet"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-servlets"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-webapp"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-proxy"
        },
        {
          "group": "org.eclipse.jetty.http2",
          "module": "http2-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-java-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-java-client"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-client"
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.4.1"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-legacy",
          "version": {
            "requires": "2.10.0"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            }
          ]
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-placeholders",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "net.javacrumbs.json-unit",
          "module": "json-unit-core",
          "version": {
            "requires": "2.40.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "asm"
            }
          ]
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.3.1"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            }
          ]
        },
        {
          "group": "com.github.jknack",
          "module": "handlebars-helpers",
          "version": {
            "requires": "4.3.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            }
          ]
        },
        {
          "group": "commons-fileupload",
          "module": "commons-fileupload",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "wiremock-3.10.0.jar",
          "url": "wiremock-3.10.0.jar",
          "size": 4250195,
          "sha512": "3d4df9e4b03dfbfe8fdd5d4f7197b013947bbbb10fa3430b4c9b3bba433d12eff7e773799dd994b77d4ca8909401157bc99f7dbca914b8f65e67d44a164baefc",
          "sha256": "44585eb176314ed15989a18c2b68b235008ef7acea150a6de8b36eb63c67cc27",
          "sha1": "cde4d0bb118de156c2f8a62894ea21ca4b58ee2d",
          "md5": "50a8134eaef5a1d40094de3bb6299373"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-bom",
          "version": {
            "requires": "11.0.24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-servlet"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-servlets"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-webapp"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-proxy"
        },
        {
          "group": "org.eclipse.jetty.http2",
          "module": "http2-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-java-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-java-client"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-client"
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.4.1"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-legacy",
          "version": {
            "requires": "2.10.0"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            }
          ]
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-placeholders",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "net.javacrumbs.json-unit",
          "module": "json-unit-core",
          "version": {
            "requires": "2.40.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "asm"
            }
          ]
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.3.1"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            }
          ]
        },
        {
          "group": "com.github.jknack",
          "module": "handlebars-helpers",
          "version": {
            "requires": "4.3.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            }
          ]
        },
        {
          "group": "commons-fileupload",
          "module": "commons-fileupload",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.1"
          },
          "reason": "Pinning this above the transitive version from json-path to get CVE fix"
        }
      ],
      "files": [
        {
          "name": "wiremock-3.10.0.jar",
          "url": "wiremock-3.10.0.jar",
          "size": 4250195,
          "sha512": "3d4df9e4b03dfbfe8fdd5d4f7197b013947bbbb10fa3430b4c9b3bba433d12eff7e773799dd994b77d4ca8909401157bc99f7dbca914b8f65e67d44a164baefc",
          "sha256": "44585eb176314ed15989a18c2b68b235008ef7acea150a6de8b36eb63c67cc27",
          "sha1": "cde4d0bb118de156c2f8a62894ea21ca4b58ee2d",
          "md5": "50a8134eaef5a1d40094de3bb6299373"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wiremock-3.10.0-sources.jar",
          "url": "wiremock-3.10.0-sources.jar",
          "size": 3898011,
          "sha512": "8eb9718078e7ffa87c7ec5f1cf6f2c2b3acea6f3478d38b85ca4606e7f27fdd2fdd555ecee150d3f4ec563bc856f36314b1edc4dbf6b8b863428723ad6060680",
          "sha256": "e46bed89b2d9554bf8e2a7d6481ff3ac7f9fa9a3e3a5eb30f72bf43102e82faa",
          "sha1": "6beeeb48e1a776e8457cc5ea2d02bd55abc11dd8",
          "md5": "b3cac73c242eb2f40af59878b373267a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wiremock-3.10.0-javadoc.jar",
          "url": "wiremock-3.10.0-javadoc.jar",
          "size": 2506621,
          "sha512": "b4042c03231fba9d9c7074eaf37b2bbe994c29130a03e1f4a578e72989f54ad402ba7ada924880b1ee1ef9895834d8280d719ce5b7548c12c035f173e0292332",
          "sha256": "ae72258dd7b38b9d311ecf116c447177dce5069e0e8c6770621c98d5663023cc",
          "sha1": "f3f33c9306d42d720628d0655666388ba0d22e66",
          "md5": "8eba5b683445cdc6ca71da83382d170d"
        }
      ]
    }
  ]
}
