{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.4.4.jar",
          "url": "spring-boot-3.4.4.jar",
          "size": 1770953,
          "sha512": "faace902b6546aa62bae1495a9593126c2d9067531632c137933f479f894f1dfb6923a4c30d709b55e65893e3edb5ea70a3f20e5d2795088456c64fb8a601dda",
          "sha256": "f134d42d19c1f707408e2ce6ace8d5887a9e7c3e50a351a75ada80afbbd6ecaf",
          "sha1": "f9dbe14c2e5e35a2cd27156802ea6b7c42ab34fd",
          "md5": "c331dfe3b43f06335abfbfc9627c4947"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.4.4.jar",
          "url": "spring-boot-3.4.4.jar",
          "size": 1770953,
          "sha512": "faace902b6546aa62bae1495a9593126c2d9067531632c137933f479f894f1dfb6923a4c30d709b55e65893e3edb5ea70a3f20e5d2795088456c64fb8a601dda",
          "sha256": "f134d42d19c1f707408e2ce6ace8d5887a9e7c3e50a351a75ada80afbbd6ecaf",
          "sha1": "f9dbe14c2e5e35a2cd27156802ea6b7c42ab34fd",
          "md5": "c331dfe3b43f06335abfbfc9627c4947"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.4.4-javadoc.jar",
          "url": "spring-boot-3.4.4-javadoc.jar",
          "size": 2465926,
          "sha512": "0d44facd659b79b6e756335ff4d85b81cd2bded1fa9e6c6ac4084d5dbe26ab01552d9d402f923f3a1651a95a198edd43186b687595e650e609edb4e224e22284",
          "sha256": "f24e94d5fd9e701024981fb3f7802a162e36c97cb89b7c279cce0e97e2e360bb",
          "sha1": "b97c785e1717e7597e67266fe9bf11d374cb0338",
          "md5": "5117c918bdc95b76a773924045212802"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.4.4-sources.jar",
          "url": "spring-boot-3.4.4-sources.jar",
          "size": 1186278,
          "sha512": "7f699c3a8dc3613b262cbc12ec97be676dc75ce4b576dd848ec49f95f07e2fc21c447a53697c77e059ea94adda44bf36400e30a7c2520c569e8cc6eb08b60d4a",
          "sha256": "e7027733bfcb78d31e6bb2f9c60c33361dee62cbbfbddb212f367f0f3d299d84",
          "sha1": "2719d022e12ff073cb46b657ff88324630bbf713",
          "md5": "09d34118a1cde73f322cac8805d8de14"
        }
      ]
    }
  ]
}
