{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-params",
    "version": "5.11.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.11.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.11.4"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.11.4.jar",
          "url": "junit-jupiter-params-5.11.4.jar",
          "size": 591594,
          "sha512": "a3febda98ac0ede59b6b92eb6034251bc7b200052d44f13b4413e3c7b467920c02f8e4af3376f4f6e4653bdb046660bc8938b44e8577daa3bfaeb5328461e32e",
          "sha256": "02a6e015de7ce94ac7f256e7fa05b8091dea861fe79a555a7993313d0f6c7d96",
          "sha1": "e4c86fbe2a39c60c6b87260ef7f7e7c1a1906481",
          "md5": "2eee588489ec62b5134fa04cff32592c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.11.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.11.4"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.11.4.jar",
          "url": "junit-jupiter-params-5.11.4.jar",
          "size": 591594,
          "sha512": "a3febda98ac0ede59b6b92eb6034251bc7b200052d44f13b4413e3c7b467920c02f8e4af3376f4f6e4653bdb046660bc8938b44e8577daa3bfaeb5328461e32e",
          "sha256": "02a6e015de7ce94ac7f256e7fa05b8091dea861fe79a555a7993313d0f6c7d96",
          "sha1": "e4c86fbe2a39c60c6b87260ef7f7e7c1a1906481",
          "md5": "2eee588489ec62b5134fa04cff32592c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.11.4-javadoc.jar",
          "url": "junit-jupiter-params-5.11.4-javadoc.jar",
          "size": 326786,
          "sha512": "f7b866eed41dee5880cef3694f1b0e727b8941b172875487050f2d3704d9ee15823c238e7465c19d6ef992763dbbdaeff9d23c5af16a057c013a4524951a9e0d",
          "sha256": "7a12c571d0e5bff0a26fcc94dd3cc95f65d722922f4027bb5ccce18b953429e7",
          "sha1": "bad93d6f9170ed0e600004870a0207b49e9043c7",
          "md5": "31ae52656c392963f4e21a7ed1173ed3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.11.4-sources.jar",
          "url": "junit-jupiter-params-5.11.4-sources.jar",
          "size": 86718,
          "sha512": "18949057451a87fabdc27bc7844292a8222a5c0dab437b9ef337e12a7338d8620d11b42d7042d5dc110ebc15714fe3c256bd8f85b3033d75a13c17241f6d204f",
          "sha256": "073ce1b0f7fa3ee1e89e301e5f92078058ce7702ba662652cc3932d9573137bc",
          "sha1": "2a8cedde21fd75650a78c825f0439ccab44a5217",
          "md5": "bcab278e9a66c96f108a3ea98710aea7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.11.4.jar",
          "url": "junit-jupiter-params-5.11.4.jar",
          "size": 591594,
          "sha512": "a3febda98ac0ede59b6b92eb6034251bc7b200052d44f13b4413e3c7b467920c02f8e4af3376f4f6e4653bdb046660bc8938b44e8577daa3bfaeb5328461e32e",
          "sha256": "02a6e015de7ce94ac7f256e7fa05b8091dea861fe79a555a7993313d0f6c7d96",
          "sha1": "e4c86fbe2a39c60c6b87260ef7f7e7c1a1906481",
          "md5": "2eee588489ec62b5134fa04cff32592c"
        }
      ]
    }
  ]
}
