{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-autoconfigure",
    "version": "3.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.4.4.jar",
          "url": "spring-boot-autoconfigure-3.4.4.jar",
          "size": 2011991,
          "sha512": "490b5219d2bf224c6b6cde0ce49bf0cddc9d163e46d031ba59371ca4c6d76f10cbb0899b035af6ad10bce092e7651904b8eeee4ee8cbdb5ebc7cac25ca3b3c32",
          "sha256": "04a3b4f7c4e0ab39fb8b4dd77a2092ed5c036961133d278060af14455dc55d39",
          "sha1": "5ebc8c0682374768ee6eac9acf12f41e76762207",
          "md5": "36f0a25f6f5d8942b18d0f508144c9e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.4.4.jar",
          "url": "spring-boot-autoconfigure-3.4.4.jar",
          "size": 2011991,
          "sha512": "490b5219d2bf224c6b6cde0ce49bf0cddc9d163e46d031ba59371ca4c6d76f10cbb0899b035af6ad10bce092e7651904b8eeee4ee8cbdb5ebc7cac25ca3b3c32",
          "sha256": "04a3b4f7c4e0ab39fb8b4dd77a2092ed5c036961133d278060af14455dc55d39",
          "sha1": "5ebc8c0682374768ee6eac9acf12f41e76762207",
          "md5": "36f0a25f6f5d8942b18d0f508144c9e8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.4.4-javadoc.jar",
          "url": "spring-boot-autoconfigure-3.4.4-javadoc.jar",
          "size": 3113655,
          "sha512": "49e4f5e518c904d623723ae9a042a05324652b1bb8c010e3be4d5c96772fb472904c972d85a8eb47b5ef2594ee4916975a8d7358468a50c6682135232f2dc1fc",
          "sha256": "e90595cc5d4f8db41a6851ed5869903edeb383727c7b19363432b7728a031124",
          "sha1": "1eed50e1551675a94f5a41ef32f9731551298458",
          "md5": "7d02b2eee650cba40e5b4a52c008942b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.4.4-sources.jar",
          "url": "spring-boot-autoconfigure-3.4.4-sources.jar",
          "size": 1154946,
          "sha512": "3fa38d588e14b4dc6bd02da62d03a5bb8f671ef2778f4b975547e01528d8d173a788cbbf336b7bd581bacbb2f611f04569ebc2522dd2272e96cc5b55558532c9",
          "sha256": "55ac02e90697d7c82e45a58c876b0678479d3e7cdd60209604d8eb9ceb88ce00",
          "sha1": "2e1b293d2cdcd796ae98f29cce6c6d7683ff72ba",
          "md5": "0048784bc74a02b79e56ee379ee47bc6"
        }
      ]
    }
  ]
}
