{
  "formatVersion": "1.1",
  "component": {
    "group": "org.niis.xrd4j",
    "module": "rest",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20240303"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "rest-0.6.0.jar",
          "url": "rest-0.6.0.jar",
          "size": 92075,
          "sha512": "71fd3dd1331fd1bb815ba7bd2b442a72c94f691b1c0b133ae1507246206d399cde8d3e4ce5f66668793daf1f7fe0dfe3c921deb163c215209ce360776bdc0e88",
          "sha256": "6d317d3747ed0db71a032c1737d76d259e013f60f63cefe02b881f471ec90e3f",
          "sha1": "d249b8421809eaf1cfb2fbf89623f03b2126e9bb",
          "md5": "815dd76d583787bebad1c9663c45c722"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20240303"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "rest-0.6.0.jar",
          "url": "rest-0.6.0.jar",
          "size": 92075,
          "sha512": "71fd3dd1331fd1bb815ba7bd2b442a72c94f691b1c0b133ae1507246206d399cde8d3e4ce5f66668793daf1f7fe0dfe3c921deb163c215209ce360776bdc0e88",
          "sha256": "6d317d3747ed0db71a032c1737d76d259e013f60f63cefe02b881f471ec90e3f",
          "sha1": "d249b8421809eaf1cfb2fbf89623f03b2126e9bb",
          "md5": "815dd76d583787bebad1c9663c45c722"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rest-0.6.0-sources.jar",
          "url": "rest-0.6.0-sources.jar",
          "size": 95900,
          "sha512": "9dea5ccba5ef4340e88d7c7c57bf0b9ed6ac4002a8d36a0999041dce2da74ebb4679345ca1fbd7b6ec4bfbfb6ca5abf25f57d9864afc6dea1d5b61efa6dc57b8",
          "sha256": "2748d636b79297adfb43542bafb21216fdf3d068618063688bf12b1e85476395",
          "sha1": "7a4072bfa6742b6d8deecd1d9094be4ae6bf2ec4",
          "md5": "4808d234459e9f033bd2c5d02a5e7c59"
        }
      ]
    }
  ]
}
