0.id=FI_TEST.GOV.9876543-1.Wiremock.format1.v1
0.path=/FI_TEST/GOV/9876543-1/Wiremock/format1.v1
0.verb=get
0.request.encrypted=true
0.response.encrypted=true
1.id=FI_TEST.GOV.9876543-1.Wiremock.format2.v1
1.path=/FI_TEST/GOV/9876543-1/Wiremock/format2.v1
1.verb=get
1.request.encrypted=true
1.response.encrypted=true
2.id=FI_TEST.GOV.9876543-1.Wiremock.format3.v1
2.path=/FI_TEST/GOV/9876543-1/Wiremock/format3.v1
2.verb=get
2.request.encrypted=true
2.response.encrypted=true
3.id=FI_TEST.GOV.9876543-1.Wiremock.format4.v1
3.path=/FI_TEST/GOV/9876543-1/Wiremock/format4.v1
3.verb=get
3.request.encrypted=false
3.response.encrypted=false
4.id=FI_TEST.GOV.9876543-1.Wiremock.format5.v1
4.path=/FI_TEST/GOV/9876543-1/Wiremock/format5.v1
4.verb=get
4.request.encrypted=true
4.response.encrypted=true
5.id=FI_TEST.GOV.9876543-1.Wiremock.format6.v1
5.path=/FI_TEST/GOV/9876543-1/Wiremock/format6.v1
5.verb=get
5.request.encrypted=true
5.response.encrypted=true

