{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.groovy",
    "module": "groovy-bom",
    "version": "4.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-ant",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-astbuilder",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-cli-commons",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-cli-picocli",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-console",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-contracts",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-datetime",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-dateutil",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-docgenerator",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-ginq",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-groovydoc",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-groovysh",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-jmx",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-jsr223",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-macro",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-macro-library",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-nio",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-servlet",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-sql",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-swing",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-templates",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-test",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-test-junit5",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-testng",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-toml",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-typecheckers",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-yaml",
          "version": {
            "requires": "4.0.22"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-ant",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-astbuilder",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-cli-commons",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-cli-picocli",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-console",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-contracts",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-datetime",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-dateutil",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-docgenerator",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-ginq",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-groovydoc",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-groovysh",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-jmx",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-jsr223",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-macro",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-macro-library",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-nio",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-servlet",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-sql",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-swing",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-templates",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-test",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-test-junit5",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-testng",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-toml",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-typecheckers",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "4.0.22"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-yaml",
          "version": {
            "requires": "4.0.22"
          }
        }
      ]
    }
  ]
}
