{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.platform",
    "module": "junit-platform-commons",
    "version": "1.11.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.11.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-platform-commons-1.11.4.jar",
          "url": "junit-platform-commons-1.11.4.jar",
          "size": 142008,
          "sha512": "0719cd50d439dc303310ff350ca3ea01df077e80290836a7489adfa3d03cca36ee97537cca9df83822ca9166f55c0cbcafa9f1c4605553b36d0cf342ba3a1fb7",
          "sha256": "9edd969b0d0670c54105bc91ae79bd1c6f503e12115faba82073b84c86bbc334",
          "sha1": "8898eea3ed0da2641548d602c3e308804f166303",
          "md5": "7e51034e6332ac61c11f9a00eb1d9471"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.11.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "junit-platform-commons-1.11.4.jar",
          "url": "junit-platform-commons-1.11.4.jar",
          "size": 142008,
          "sha512": "0719cd50d439dc303310ff350ca3ea01df077e80290836a7489adfa3d03cca36ee97537cca9df83822ca9166f55c0cbcafa9f1c4605553b36d0cf342ba3a1fb7",
          "sha256": "9edd969b0d0670c54105bc91ae79bd1c6f503e12115faba82073b84c86bbc334",
          "sha1": "8898eea3ed0da2641548d602c3e308804f166303",
          "md5": "7e51034e6332ac61c11f9a00eb1d9471"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-commons-1.11.4-javadoc.jar",
          "url": "junit-platform-commons-1.11.4-javadoc.jar",
          "size": 368000,
          "sha512": "ff66254b83cd69379ee33016a398b2993bcb96d260c60a1c688bcad42aeda766997b747033007005e3a2e0198e252c7d4ba56fe71c8ae89dc7b6db6e3bbc04a9",
          "sha256": "00c608d5857c396b8cc55c0cd2e2b9e5138dc17771674b6fb4ed341c262e8190",
          "sha1": "cf7838ac67f8172574c50fb63b0e129c1dc369c9",
          "md5": "edfe093a4dc92914a0be5ed27bfca4d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-commons-1.11.4-sources.jar",
          "url": "junit-platform-commons-1.11.4-sources.jar",
          "size": 96980,
          "sha512": "5ccd1e8d1d1f5e946d21a294a9f6bb0d2281ff1728a539d041e8483e555b1f68366e16cfbfbc02a892b15d5cdeaf392ed3d0da658ddaeb931ddc0449c40ad889",
          "sha256": "a2f0c562a7fe4066044d93bb20ce527b4669c1ddaefca2244a53356db747c5e2",
          "sha1": "1acfe264ada9081bba59c937a8b0cae0619491bc",
          "md5": "a869b20bea5f1eede7fc505ade1cbc8c"
        }
      ]
    }
  ]
}
