{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-expression",
    "version": "6.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.2.5.jar",
          "url": "spring-expression-6.2.5.jar",
          "size": 317832,
          "sha512": "32f79f254f323fc24bca13e48ebd78cb69ba3a407c6b55f57e63756a9f8d05047e2903ba0dadddf079fa924c8d3bc62854a2e1214700af95a5b724b5e14b7894",
          "sha256": "ec76c41d4e45779b48ae10020322b32ecb2e2f4f2d930b0d93844a44490d76c5",
          "sha1": "cb39181911dabe3b3d9992c4b4da38468726ea72",
          "md5": "b681c4349ef4118393da6ea6803f0381"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.2.5.jar",
          "url": "spring-expression-6.2.5.jar",
          "size": 317832,
          "sha512": "32f79f254f323fc24bca13e48ebd78cb69ba3a407c6b55f57e63756a9f8d05047e2903ba0dadddf079fa924c8d3bc62854a2e1214700af95a5b724b5e14b7894",
          "sha256": "ec76c41d4e45779b48ae10020322b32ecb2e2f4f2d930b0d93844a44490d76c5",
          "sha1": "cb39181911dabe3b3d9992c4b4da38468726ea72",
          "md5": "b681c4349ef4118393da6ea6803f0381"
        }
      ]
    }
  ]
}
