{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context",
    "version": "6.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-6.2.5.jar",
          "url": "spring-context-6.2.5.jar",
          "size": 1353640,
          "sha512": "df0309bc4d2967a03592637356839ea0b2142e4def7af75fb197ca0115c4d7ea23ff5f8157e19e70c289cf3cc9c35abac5f1bdb442952d6c06b2191d344fcf1e",
          "sha256": "21941e0c9f23310c78403f35a624b27f3a1301f1ccf5de250d7478956e7bab51",
          "sha1": "237de0c3afca2099ab497cc7464726c02b8ab5c5",
          "md5": "d7b865642c0898e1f0e492b58c4d63fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-6.2.5.jar",
          "url": "spring-context-6.2.5.jar",
          "size": 1353640,
          "sha512": "df0309bc4d2967a03592637356839ea0b2142e4def7af75fb197ca0115c4d7ea23ff5f8157e19e70c289cf3cc9c35abac5f1bdb442952d6c06b2191d344fcf1e",
          "sha256": "21941e0c9f23310c78403f35a624b27f3a1301f1ccf5de250d7478956e7bab51",
          "sha1": "237de0c3afca2099ab497cc7464726c02b8ab5c5",
          "md5": "d7b865642c0898e1f0e492b58c4d63fc"
        }
      ]
    }
  ]
}
