{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "6.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.2.5.jar",
          "url": "spring-web-6.2.5.jar",
          "size": 2087110,
          "sha512": "75f661b010266556b3450834e5de613cf4e189443e58e4eb900d3d87a29143086f4da8a4cb92aa4ab2c66d043a9690bc61037b76294d79fdf1e223b1e6349c2a",
          "sha256": "85f0c1acaf033a5f7abdcaf348f1dd2cebe1f77687ee77f05e8cb66bfbc6fecf",
          "sha1": "b42d2c0acbe05bad4c849883aa8816c25b6c1d94",
          "md5": "e0ef0fc6c6d3b55efa9829426452e09f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.2.5.jar",
          "url": "spring-web-6.2.5.jar",
          "size": 2087110,
          "sha512": "75f661b010266556b3450834e5de613cf4e189443e58e4eb900d3d87a29143086f4da8a4cb92aa4ab2c66d043a9690bc61037b76294d79fdf1e223b1e6349c2a",
          "sha256": "85f0c1acaf033a5f7abdcaf348f1dd2cebe1f77687ee77f05e8cb66bfbc6fecf",
          "sha1": "b42d2c0acbe05bad4c849883aa8816c25b6c1d94",
          "md5": "e0ef0fc6c6d3b55efa9829426452e09f"
        }
      ]
    }
  ]
}
