/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {  
    repositories {
        gradlePluginPortal()
    }
}

plugins {   
    
}

dependencyResolutionManagement {    
    repositories {
        mavenLocal()
        maven {
            url = uri("https://artifactory.niis.org/xroad-maven-releases")
        }

        maven {
            url = uri("https://artifactory.niis.org/xroad-maven-snapshots")
        }

        maven {
            url = uri("https://repo.maven.apache.org/maven2/")
        }
    }
}

rootProject.name = "rest-adapter-service"


