/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

plugins {

}

dependencyResolutionManagement {
    repositories {
        gradlePluginPortal()
        mavenLocal()
        maven {
            url = uri("https://artifactory.niis.org/xroad-maven-releases")
            mavenContent {
                releasesOnly()
            }
        }
        maven {
            url = uri("https://artifactory.niis.org/xroad-maven-snapshots")
            mavenContent {
                snapshotsOnly()
            }
        }
        maven {
            url = uri("https://repo.maven.apache.org/maven2/")
        }
        mavenCentral()
    }
}

rootProject.name = "rest-adapter-service"


