{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-framework-bom",
    "version": "5.3.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-indexer",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-instrument",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jms",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-orm",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-oxm",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-r2dbc",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-websocket",
          "version": {
            "requires": "5.3.39"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-indexer",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-instrument",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jms",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-orm",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-oxm",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-r2dbc",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.3.39"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-websocket",
          "version": {
            "requires": "5.3.39"
          }
        }
      ]
    }
  ]
}
