{
  "formatVersion": "1.1",
  "component": {
    "group": "org.niis.xrd4j",
    "module": "common",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.sun.xml.messaging.saaj",
          "module": "saaj-impl",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.6.0.jar",
          "url": "common-0.6.0.jar",
          "size": 125138,
          "sha512": "27bf7f3deda131ff3157704e4398fb7a7060736e55183a7aa81e4ba74260aed9d4bebd839dda91ca88dd532a06f9bc7b7a5aba40b5ac0bef32fb597bb1d2fcee",
          "sha256": "158f03898c0a6ceb37e252116fa293d4fcc7f3f55ec9b46d5e5ebd3b65b16a57",
          "sha1": "c12edec6a2752c62be16ae7b3ed2ac32a6148651",
          "md5": "2518b49254cf84e26ff7dfc0ae82abcc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.sun.xml.messaging.saaj",
          "module": "saaj-impl",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.6.0.jar",
          "url": "common-0.6.0.jar",
          "size": 125138,
          "sha512": "27bf7f3deda131ff3157704e4398fb7a7060736e55183a7aa81e4ba74260aed9d4bebd839dda91ca88dd532a06f9bc7b7a5aba40b5ac0bef32fb597bb1d2fcee",
          "sha256": "158f03898c0a6ceb37e252116fa293d4fcc7f3f55ec9b46d5e5ebd3b65b16a57",
          "sha1": "c12edec6a2752c62be16ae7b3ed2ac32a6148651",
          "md5": "2518b49254cf84e26ff7dfc0ae82abcc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-0.6.0-sources.jar",
          "url": "common-0.6.0-sources.jar",
          "size": 136848,
          "sha512": "f0957861357b0e5d33b52b68be64cffa02ebbda9a7a76b736669c1dabe76c4ee7af4b39904506461eeca6ec2900d14c34f7dc2b705bea2c83fb8854055317dc0",
          "sha256": "e5028109ed2e5e5a233f338e678b966838b93334f10656ba380cea55164a390a",
          "sha1": "f691d2c976c8a087c26b76f9534272d1f6fee770",
          "md5": "64044ad648e8b1be1c0a445e04c19efc"
        }
      ]
    }
  ]
}
