{
  "formatVersion": "1.1",
  "component": {
    "group": "org.wiremock.integrations",
    "module": "wiremock-spring-boot",
    "version": "3.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.wiremock",
          "module": "wiremock-jetty12",
          "version": {
            "requires": "3.10.0"
          },
          "excludes": [
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlet"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlets"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-webapp"
            },
            {
              "group": "org.eclipse.jetty.http2",
              "module": "http2-server"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlet"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlets"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-webapp"
            },
            {
              "group": "org.eclipse.jetty.http2",
              "module": "http2-server"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.13"
          },
          "excludes": [
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlet"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlets"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-webapp"
            },
            {
              "group": "org.eclipse.jetty.http2",
              "module": "http2-server"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          },
          "excludes": [
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlet"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlets"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-webapp"
            },
            {
              "group": "org.eclipse.jetty.http2",
              "module": "http2-server"
            }
          ]
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.11.2"
          },
          "excludes": [
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlet"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlets"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-webapp"
            },
            {
              "group": "org.eclipse.jetty.http2",
              "module": "http2-server"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "wiremock-spring-boot-3.6.0.jar",
          "url": "wiremock-spring-boot-3.6.0.jar",
          "size": 24977,
          "sha512": "b1a2c35863a77f5db1a659170db59852b8dcfb29ec70e3e34e525964d4cf560db8acd4926dccb7de3253bb0954da8a9ee29a63271e6ceae5da42fa40b61e7a00",
          "sha256": "cd2eed948f855e8507c58eada1e74d02abe1f68dbdc4b8c07743864f5a3df549",
          "sha1": "e6b3c6e1dfdd64efeef8ecca9451b67b7d1aaa0d",
          "md5": "578582719045e9e96395c46760bffa58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-bom",
          "version": {
            "requires": "12.0.15"
          },
          "excludes": [
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlet"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlets"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-webapp"
            },
            {
              "group": "org.eclipse.jetty.http2",
              "module": "http2-server"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.wiremock",
          "module": "wiremock-jetty12",
          "version": {
            "requires": "3.10.0"
          },
          "excludes": [
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlet"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlets"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-webapp"
            },
            {
              "group": "org.eclipse.jetty.http2",
              "module": "http2-server"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.4.1"
          },
          "excludes": [
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlet"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlets"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-webapp"
            },
            {
              "group": "org.eclipse.jetty.http2",
              "module": "http2-server"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.13"
          },
          "excludes": [
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlet"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlets"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-webapp"
            },
            {
              "group": "org.eclipse.jetty.http2",
              "module": "http2-server"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          },
          "excludes": [
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlet"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlets"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-webapp"
            },
            {
              "group": "org.eclipse.jetty.http2",
              "module": "http2-server"
            }
          ]
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.11.2"
          },
          "excludes": [
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlet"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-servlets"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "jetty-webapp"
            },
            {
              "group": "org.eclipse.jetty.http2",
              "module": "http2-server"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.0"
          },
          "reason": "version 1.24.0 has a vulnerability"
        }
      ],
      "files": [
        {
          "name": "wiremock-spring-boot-3.6.0.jar",
          "url": "wiremock-spring-boot-3.6.0.jar",
          "size": 24977,
          "sha512": "b1a2c35863a77f5db1a659170db59852b8dcfb29ec70e3e34e525964d4cf560db8acd4926dccb7de3253bb0954da8a9ee29a63271e6ceae5da42fa40b61e7a00",
          "sha256": "cd2eed948f855e8507c58eada1e74d02abe1f68dbdc4b8c07743864f5a3df549",
          "sha1": "e6b3c6e1dfdd64efeef8ecca9451b67b7d1aaa0d",
          "md5": "578582719045e9e96395c46760bffa58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wiremock-spring-boot-3.6.0-sources.jar",
          "url": "wiremock-spring-boot-3.6.0-sources.jar",
          "size": 12375,
          "sha512": "c8208f5a23470da093580dfb4f41df48f1b776de57c041860461ae4f48e0fa7fd8aab5b9e3b1116044d51ed4f8cc5a78d41ede16e63a0deb21b695335ee25f37",
          "sha256": "fe5542c0e67cd0adb73618b83d426639e16aba4f67189ae1b4919e1151804105",
          "sha1": "a5677904b19afdec0c94f8418f83596478bc67b4",
          "md5": "5eaa6f42a713c51aa93be60a37c67f38"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wiremock-spring-boot-3.6.0-javadoc.jar",
          "url": "wiremock-spring-boot-3.6.0-javadoc.jar",
          "size": 106620,
          "sha512": "b46ad06962a3be42ce1050fab3ea41d676ffc92109ea647c53745538256d5027605a89600b62b7ac89dc8d33cac6c2928ef17878fc71376e00ebc724d2e9152e",
          "sha256": "1d8bb6befb93b860ba109671312ab28b672f231ee8c0d16d08959424446f92b4",
          "sha1": "ce7efc5fa393c3a859c430a174731c937cb44b50",
          "md5": "d81c8904cda74106831ad9a574dce658"
        }
      ]
    }
  ]
}
