{
  "formatVersion": "1.1",
  "component": {
    "group": "org.niis.xrd4j",
    "module": "server",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.niis.xrd4j",
          "module": "common",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "server-0.6.0.jar",
          "url": "server-0.6.0.jar",
          "size": 95758,
          "sha512": "f338e727ec1974ad95221284b74fda554bcf23ce05ec2dca6bda90361d9a81082b7ff67a452f5b36ba1e41157735ac5c782f76b6ce5c68966779712f92d95b63",
          "sha256": "2ed98d36ecd23c7b8faba6c987bab4c04e25221b4de612dcb3d2a6dfd7088fa4",
          "sha1": "891471a69b2346c553ee5e8aefe74bf30a6b0414",
          "md5": "4322b5efd43cf0849b72090af2f5d63f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.niis.xrd4j",
          "module": "common",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "server-0.6.0.jar",
          "url": "server-0.6.0.jar",
          "size": 95758,
          "sha512": "f338e727ec1974ad95221284b74fda554bcf23ce05ec2dca6bda90361d9a81082b7ff67a452f5b36ba1e41157735ac5c782f76b6ce5c68966779712f92d95b63",
          "sha256": "2ed98d36ecd23c7b8faba6c987bab4c04e25221b4de612dcb3d2a6dfd7088fa4",
          "sha1": "891471a69b2346c553ee5e8aefe74bf30a6b0414",
          "md5": "4322b5efd43cf0849b72090af2f5d63f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "server-0.6.0-sources.jar",
          "url": "server-0.6.0-sources.jar",
          "size": 94790,
          "sha512": "32a54d959e5e3f3767f7ca24232da50be70a91f7b4db9f21d4d19fc490d81ce75860c4476ebbb770074e6386aa1879421e6a92767a1463a77e28b413f9b73f48",
          "sha256": "d78dfeb9049700960e8b3ee5e20395f6907291f2d91f5d1bdbc647d6c6cc25e0",
          "sha1": "469043ad42f2c248b6844aaae03c9c57a0c984f5",
          "md5": "4d9f1b258c6e5059ca3af3f97ab06bc7"
        }
      ]
    }
  ]
}
