{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.platform",
    "module": "junit-platform-launcher",
    "version": "1.11.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.11.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-engine",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-platform-launcher-1.11.4.jar",
          "url": "junit-platform-launcher-1.11.4.jar",
          "size": 189006,
          "sha512": "92990d325829a9a70a0dc5ab1c20e3146ebd4859363b713f7a2b2858192df3115e992869c0ca3155789515cefb2c868c02a106bcc4fa4a796b8f09777b4911f0",
          "sha256": "d7430bd029e7fcced53ee445e4d2d1a8a1e043ea4c4df43b6335a857f79761ae",
          "sha1": "3d83c201899d8c5e74e1a5d628eab900342a0e48",
          "md5": "f8835afc4e99e5194c4a34d9b80a65e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.11.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-engine",
          "version": {
            "requires": "1.11.4"
          }
        }
      ],
      "files": [
        {
          "name": "junit-platform-launcher-1.11.4.jar",
          "url": "junit-platform-launcher-1.11.4.jar",
          "size": 189006,
          "sha512": "92990d325829a9a70a0dc5ab1c20e3146ebd4859363b713f7a2b2858192df3115e992869c0ca3155789515cefb2c868c02a106bcc4fa4a796b8f09777b4911f0",
          "sha256": "d7430bd029e7fcced53ee445e4d2d1a8a1e043ea4c4df43b6335a857f79761ae",
          "sha1": "3d83c201899d8c5e74e1a5d628eab900342a0e48",
          "md5": "f8835afc4e99e5194c4a34d9b80a65e0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-launcher-1.11.4-javadoc.jar",
          "url": "junit-platform-launcher-1.11.4-javadoc.jar",
          "size": 346525,
          "sha512": "2b8b3dcb5e0167a1e0f3618c877d19b76e95f116a45fb9bf834bf3454c1c0d1f9dca97cc7b3f81159789ce8cabf221d62bf9a74ab81d8f259710c829196997e8",
          "sha256": "913dd2abdbc2b7c1bf547619d7c50ac6087c6b4d688f0af3b58a0dfb11a9572c",
          "sha1": "51a67d2e34b8de65bd4d5115d54f2a3d639c3d7f",
          "md5": "6ecb36e77e7a70fc3b7de282226a9f7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-launcher-1.11.4-sources.jar",
          "url": "junit-platform-launcher-1.11.4-sources.jar",
          "size": 108963,
          "sha512": "673e20788c60e63172a65f7b4dd42553db48a32ab73f91d1101f1536af03accc6d2b5da30b92bfbada498b10604d432ad7fc4ea03c71bb0bc7ce3a152c4f45ca",
          "sha256": "e560e5e7bc6eed184774f75a7b36b824e20ec818be4b991213c0d31aff4260c5",
          "sha1": "d705f6b0d147036b7d84dca5eaad35b41d64592a",
          "md5": "c0fdeeb10cf718807868490d41d2f328"
        }
      ]
    }
  ]
}
