
name: Build and Test

on:
  # Capture this event so that gradle caches are updated when a PR is merged to develop
  # More information on why: https://github.com/gradle/gradle-build-action#using-the-caches-read-only
  push:
    branches:
      - develop
    paths:
      - 'adapter/**'
      - '.github/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'adapter/**'
      - '.github/**'

jobs:
  BuildWithUnitTests:
    name: Build, test and package code
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
          gradle-home-cache-cleanup: true
          dependency-graph: generate-and-submit
          add-job-summary-as-pr-comment: always

      - name: Build and test source
        working-directory: ./adapter
        run: ./gradlew build jacocoTestReport

      - name: Test report
        env:
          NODE_OPTIONS: '--max-old-space-size=6144'
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Unit tests
          path: adapter/**/build/test-results/**/TEST-*.xml
          reporter: java-junit
          list-suites: 'failed'
          list-tests: 'failed'

  IntTestsEncrypted:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    needs: BuildWithUnitTests
    name: Encrypted integration tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
          gradle-home-cache-cleanup: true
          dependency-graph: generate-and-submit
          add-job-summary-as-pr-comment: always

      - name: Integration tests
        working-directory: ./adapter
        run: ./gradlew intTest jacocoTestReport -PcustomPropertiesDir=src/test/resources/application-intTest-properties/encrypted

      - name: Test report
        env:
          NODE_OPTIONS: '--max-old-space-size=6144'
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Integration tests encrypted
          path: adapter/**/build/test-results/**/TEST-*.xml
          reporter: java-junit
          list-suites: 'failed'
          list-tests: 'failed'

  IntTestsPlaintext:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    needs: BuildWithUnitTests
    name: Plaintext integration tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
          gradle-home-cache-cleanup: true
          dependency-graph: generate-and-submit
          add-job-summary-as-pr-comment: always

      - name: Integration Tests
        working-directory: ./adapter
        run: ./gradlew intTest jacocoTestReport

      - name: Test report
        env:
          NODE_OPTIONS: '--max-old-space-size=6144'
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Integration tests plaintext
          path: adapter/**/build/test-results/**/TEST-*.xml
          reporter: java-junit
          list-suites: 'failed'
          list-tests: 'failed'
