{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-api",
    "version": "5.11.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.11.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.11.4.jar",
          "url": "junit-jupiter-api-5.11.4.jar",
          "size": 216413,
          "sha512": "4def96fbd316a49a5d8646d9341fb68865b4ca2e6c72efc05e5f87b357ea0a66fd7edccf02f53d32d8be13530b04d8cad99035d7c2e8697fef526f0e5959c928",
          "sha256": "ab83ef9e51ac4597d59d26b4b58812129550e2f579a404c8af7d09f5ce5b4293",
          "sha1": "308315b28e667db4091b2ba1f7aa220d1ddadb97",
          "md5": "e055a09339f2abd6ad3dc6d206ff1c3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.11.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.11.4"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.11.4.jar",
          "url": "junit-jupiter-api-5.11.4.jar",
          "size": 216413,
          "sha512": "4def96fbd316a49a5d8646d9341fb68865b4ca2e6c72efc05e5f87b357ea0a66fd7edccf02f53d32d8be13530b04d8cad99035d7c2e8697fef526f0e5959c928",
          "sha256": "ab83ef9e51ac4597d59d26b4b58812129550e2f579a404c8af7d09f5ce5b4293",
          "sha1": "308315b28e667db4091b2ba1f7aa220d1ddadb97",
          "md5": "e055a09339f2abd6ad3dc6d206ff1c3a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.11.4-javadoc.jar",
          "url": "junit-jupiter-api-5.11.4-javadoc.jar",
          "size": 827609,
          "sha512": "efeb6749150fbebf967acd465512eb5eb8f66c099e880276ae23eed46ef246efbc4340529e52ba8bb9dabce93ed9937d8c883cd8d5bc2067834ecfe3e359b3b8",
          "sha256": "616014c3fc8e762fd38aca2b23e4f886d62ce96acb956564bc35c3aa13cf19cd",
          "sha1": "bb37cb1edfd09d2c083a9774d366fba083cfba44",
          "md5": "da3a880b897650b52d69d06afa5e4610"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.11.4-sources.jar",
          "url": "junit-jupiter-api-5.11.4-sources.jar",
          "size": 214992,
          "sha512": "ba8f5fa212361318af73043021f474afed28dfe82abd350a6d015d819f1e46161e89a581dcfeafdbeeff56a7114cf02ba5515fbb1ef7aed3ce12223c33cf6be6",
          "sha256": "5f54639572bcafc393754f0ce89677192947c01ffe2600a597b60b59bc437f3b",
          "sha1": "c2973c17e3a51473b6827b7a5d3f7167b687f42d",
          "md5": "f559513e0e4ca73b87a878e938f29ad1"
        }
      ]
    }
  ]
}
