{
  "formatVersion": "1.1",
  "component": {
    "group": "org.wiremock",
    "module": "wiremock-jetty12",
    "version": "3.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-bom",
          "version": {
            "requires": "12.0.14"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.eclipse.jetty.ee10",
          "module": "jetty-ee10-bom",
          "version": {
            "requires": "12.0.14"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.wiremock",
          "module": "wiremock",
          "version": {
            "requires": "3.10.0"
          },
          "excludes": [
            {
              "group": "org.eclipse.jetty.http2",
              "module": "*"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-proxy"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-java-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-java-client"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-client"
        },
        {
          "group": "org.eclipse.jetty.ee10",
          "module": "jetty-ee10-servlet"
        },
        {
          "group": "org.eclipse.jetty.ee10",
          "module": "jetty-ee10-servlets"
        },
        {
          "group": "org.eclipse.jetty.ee10",
          "module": "jetty-ee10-webapp"
        },
        {
          "group": "org.eclipse.jetty.http2",
          "module": "jetty-http2-server",
          "version": {
            "requires": "12.0.14"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-java-server",
          "version": {
            "requires": "12.0.14"
          }
        }
      ],
      "files": [
        {
          "name": "wiremock-jetty12-3.10.0.jar",
          "url": "wiremock-jetty12-3.10.0.jar",
          "size": 17280,
          "sha512": "7bc0a3fafbdfe00217ffa9a8a5085a2e4f9fe37268ad680bcc6dc43c87d50c29cca49f04ecf0b301b87ce2106b6acda636677ad5d3996a52581e628f0bb1379a",
          "sha256": "867cf1bb6d43596969f812cf8ebae53ff8a2a072b89f25c5ae5e3567d36e0bd4",
          "sha1": "fb6200774618a2f83fb266d553a3aec926dabf16",
          "md5": "2f69c48d209c5e5f7cd76c7543ac955d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-bom",
          "version": {
            "requires": "12.0.14"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.eclipse.jetty.ee10",
          "module": "jetty-ee10-bom",
          "version": {
            "requires": "12.0.14"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.wiremock",
          "module": "wiremock",
          "version": {
            "requires": "3.10.0"
          },
          "excludes": [
            {
              "group": "org.eclipse.jetty.http2",
              "module": "*"
            },
            {
              "group": "org.eclipse.jetty",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-proxy"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-java-server"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-java-client"
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-client"
        },
        {
          "group": "org.eclipse.jetty.ee10",
          "module": "jetty-ee10-servlet"
        },
        {
          "group": "org.eclipse.jetty.ee10",
          "module": "jetty-ee10-servlets"
        },
        {
          "group": "org.eclipse.jetty.ee10",
          "module": "jetty-ee10-webapp"
        },
        {
          "group": "org.eclipse.jetty.http2",
          "module": "jetty-http2-server",
          "version": {
            "requires": "12.0.14"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-alpn-java-server",
          "version": {
            "requires": "12.0.14"
          }
        }
      ],
      "files": [
        {
          "name": "wiremock-jetty12-3.10.0.jar",
          "url": "wiremock-jetty12-3.10.0.jar",
          "size": 17280,
          "sha512": "7bc0a3fafbdfe00217ffa9a8a5085a2e4f9fe37268ad680bcc6dc43c87d50c29cca49f04ecf0b301b87ce2106b6acda636677ad5d3996a52581e628f0bb1379a",
          "sha256": "867cf1bb6d43596969f812cf8ebae53ff8a2a072b89f25c5ae5e3567d36e0bd4",
          "sha1": "fb6200774618a2f83fb266d553a3aec926dabf16",
          "md5": "2f69c48d209c5e5f7cd76c7543ac955d"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.wiremock",
          "module": "wiremock-jetty12",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "wiremock-jetty12-3.10.0-test-fixtures.jar",
          "url": "wiremock-jetty12-3.10.0-test-fixtures.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.wiremock",
          "name": "wiremock-jetty12-test-fixtures",
          "version": "3.10.0"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.wiremock",
          "module": "wiremock-jetty12",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "wiremock-jetty12-3.10.0-test-fixtures.jar",
          "url": "wiremock-jetty12-3.10.0-test-fixtures.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.wiremock",
          "name": "wiremock-jetty12-test-fixtures",
          "version": "3.10.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wiremock-jetty12-3.10.0-sources.jar",
          "url": "wiremock-jetty12-3.10.0-sources.jar",
          "size": 12906,
          "sha512": "8e07e061cbb701b7f40e867239504a35f1f93d99ab9bbd771df93ae2db0f2854c598dd77de058adeb5b0cd2b76a09d922c4d7c81ec9bca9222aec0f67fc6f49d",
          "sha256": "ec0072d88af71aa8c80a12cb74f2824a7035bc00a1764c742c06a30d6c312103",
          "sha1": "b3c7d1c839fb0971e792bf47272429cad31b4493",
          "md5": "0cd02e941b00895b26b774ea83a12e07"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wiremock-jetty12-3.10.0-javadoc.jar",
          "url": "wiremock-jetty12-3.10.0-javadoc.jar",
          "size": 106349,
          "sha512": "13b926b1650c1cacdc09adfe95bb81f5f0ec7e9505674593ebbfe65a8dc24b68fa992276b51173d6100dbbe022dfeb50c4b25997eabf25c2a4aba23cde410c2e",
          "sha256": "3bbc15e64de81289a8e2ff949682201319c1946d7ba4df254ec22d3ba5c0b754",
          "sha1": "ffb748ce8f3b7fb806a1f85e1ea6efc0df228c21",
          "md5": "aa6c2f592c413f500a0b51678ce3e1d8"
        }
      ]
    }
  ]
}
